// Generates src/theme.css (run: node scripts/theme.mjs): light + dark values for every palette variable the UI uses.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const tw = readFileSync(`${root}/node_modules/tailwindcss/theme.css`, "utf8");
const STEPS = ["50", "100", "200", "300", "400", "500", "600", "700", "800", "900", "950"];
const FAMILIES = ["rose", "red", "amber", "orange", "yellow", "sky", "blue", "violet", "teal", "pink"];

const light = {};
for (const family of FAMILIES) {
  light[family] = {};
  for (const step of STEPS) {
    const m = new RegExp(`--color-${family}-${step}:\\s*([^;]+);`).exec(tw);
    light[family][step] = m[1].trim();
  }
}

// Brand ramp built around the logo lime (#5CFF63); darker steps keep text contrast on white.
light.emerald = {
  50: "#f1fff1", 100: "#dfffe0", 200: "#bdffc0", 300: "#8dff92", 400: "#5cff63", 500: "#22d42c",
  600: "#139c1c", 700: "#0f7a17", 800: "#11601a", 900: "#0f4f16", 950: "#052e0b",
};

// Neutral: Tailwind slate lightness, re-hued toward the brand green with lower chroma.
light.slate = {};
for (const step of STEPS) {
  const m = new RegExp(`--color-slate-${step}:\\s*oklch\\(([\\d.]+)% ([\\d.]+) [\\d.]+\\)`).exec(tw);
  light.slate[step] = `oklch(${m[1]}% ${(Number(m[2]) * 0.55).toFixed(3)} 165)`;
}

const DARK_SURFACE = "oklch(0.185 0.012 165)";
const darkNeutralL = { 50: 0.21, 100: 0.245, 200: 0.305, 300: 0.39, 400: 0.56, 500: 0.69, 600: 0.77, 700: 0.845, 800: 0.9, 900: 0.945, 950: 0.972 };
const mix = (color, pct) => `color-mix(in oklab, ${color} ${pct}%, ${DARK_SURFACE})`;

function darkScale(scale) {
  return {
    50: mix(scale[500], 13), 100: mix(scale[500], 20), 200: mix(scale[500], 32), 300: mix(scale[500], 55),
    400: scale[400], 500: scale[500], 600: scale[400], 700: scale[300], 800: scale[200], 900: scale[100], 950: scale[50],
  };
}

const SEMANTIC = {
  light: {
    canvas: "oklch(0.975 0.004 165)",
    surface: "#ffffff",
    raised: "oklch(0.985 0.003 165)",
    line: "oklch(0.915 0.008 165)",
    ink: "oklch(0.2 0.02 165)",
    brand: "#5cff63",
    "brand-ink": "#0f7a17",
    "on-brand": "#04130a",
    glow: "rgb(34 212 44 / 0.35)",
  },
  dark: {
    canvas: "oklch(0.145 0.01 165)",
    surface: DARK_SURFACE,
    raised: "oklch(0.215 0.013 165)",
    line: "oklch(1 0 0 / 0.085)",
    ink: "oklch(0.955 0.01 165)",
    brand: "#5cff63",
    "brand-ink": "#5cff63",
    "on-brand": "#04130a",
    glow: "rgb(92 255 99 / 0.35)",
  },
};

function block(mode) {
  const lines = [];
  for (const [name, value] of Object.entries(SEMANTIC[mode])) lines.push(`  --color-${name}: ${value};`);
  for (const family of ["slate", "emerald", ...FAMILIES]) {
    const scale =
      mode === "light" ? light[family]
      : family === "slate" ? Object.fromEntries(STEPS.map((s) => [s, `oklch(${darkNeutralL[s]} 0.012 165)`]))
      : darkScale(light[family]);
    for (const step of STEPS) lines.push(`  --color-${family}-${step}: ${scale[step]};`);
  }
  return lines.join("\n");
}

const css = `/* Generated by a palette script: light and dark values for every color token.
   Dark mode mirrors each ramp (tints darken, text shades lighten), so utility classes like
   bg-rose-50 / text-rose-700 read correctly in both themes without per-component overrides. */

:root,
[data-theme="light"] {
  color-scheme: light;
${block("light")}
}

[data-theme="dark"] {
  color-scheme: dark;
${block("dark")}
}

@media print {
  :root,
  [data-theme="dark"] {
    color-scheme: light;
${block("light").replace(/^/gm, "  ")}
  }
}
`;
writeFileSync(`${root}/src/theme.css`, css);
console.log("wrote", css.length, "bytes");
